name: dart_extensions
description: A Collection of Extra Extensions to Enhance Coding.
version: 1.2.3
repository: https://github.com/MSOB7YY/dart_extensions
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  path: ^1.9.0
  intl: ^0.19.0
  string_clean_utils:
    git:
      url: https://github.com/namidaco/string_clean_utils

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  benchmarking: ^0.6.1
